apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-podmetrics-config
  namespace: default
  labels:
    app: nginx-podmetrics
  annotations:
    description: Configuração customizada do nginx

data:
  nginx.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /metrics {
            stub_status on;
            access_log  off;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

